Updated polyhedron rendering and relocated folders.
physarumAdv/Physarum_webGL pull request #9
Opened 2020-10-12 16:54 UTC by pavtiger

#7 Implemented change button for switching online and offline mode. Moreover, the style of the polyhedra was changed to a new one with no textures.

2020-10-13 20:25 UTC, kolayne requested changes
Hi! I have reviewed the PR and found several issues. Please, note that
1. I'm not closely familiar with js/NodeJS/Three.JS/..., so I might have missed some issues or saw them where they are not. If you see something like that, please, pay my attention and mark as resolved if you're sure the comment is a false positive
2. I highly recommend you fix the issues found by Codacy or ignoring them where you're sure they are not valid or relevant. Deal with them
3. I don't quite understand what is the PR about exactly, so some of my comments may not relate to the PR goal, consider referencing them in new issues and mark them as resolved in the PR
4. Next time, please, break down your changes into smaller PRs, reviewing this huge one was kind of laborious and my efficiency could drop significantly during the review

2020-10-13 20:25 UTC, kolayne commented on main_server.js
> +            req.url = req.url.replace("/lib", "/");
This is not correct. What is going to happen if I visit `/lib/123/lib/456`?

2020-10-13 20:25 UTC, kolayne commented on main_server.js
> +            req.url = req.url.replace("/scripts", "/");
Same as one of the above

2020-10-13 20:25 UTC, kolayne commented on main_server.js
> +        case pathname.startsWith("/lib"):
1. I think you should check not that `pathname` starts with `"/lib"` but that `pathname` starts with `"/lib/"`, because somewhen you may have a page with an address like `"/lib123"`
2. What happens if I visit `/lib/`? Will it give me a listing of your /lib directory? If so, do you actually expect it to do so? Probably you have to add some protection

2020-10-13 20:25 UTC, kolayne commented on main_server.js
> +        case pathname.startsWith("/scripts"):
Same as one of the above

2020-10-13 20:25 UTC, kolayne commented on physarum_ThreeJS.html
> +        <link rel="icon" href="/lib/icon.jpg">
I'd remove the leading `/` (i. e. replace `/lib/icon.jpg` with `lib/icon.jpg`) to keep the style. Furthermore, this way you will be able to add a proxy server (for example, install Nginx or something) to add a prefix to all the URLs (for example, make your project accessible from `/physarum` instead of `/` without updating sources)

2020-10-13 20:25 UTC, kolayne commented on physarum_ThreeJS.html
> +        <script type="module" src="scripts/main.js"></script>
A positive change! :)

2020-10-13 20:25 UTC, kolayne commented on scripts/main.js
> + * @param The url of a server for request
As far as I'm concerned in Doxygen `@param` should always be followed by a variable name

2020-10-13 20:25 UTC, kolayne commented on scripts/main.js
> +function httpGet(theUrl) {
`theUrl`? Why adding an article to the variable name?!

2020-10-13 20:25 UTC, kolayne commented on scripts/main.js
> +            var material = new THREE.MeshBasicMaterial({color: color, wireframe: false});
These lines seem to be independent of the `for` loop. Shouldn't they be moved above to outside of it?

2020-10-13 20:25 UTC, kolayne commented on scripts/main.js
> +    camera.rotation.y = 3.14;
Some javascript magic or a copypaste mistake?)

2020-10-13 20:25 UTC, kolayne commented on scripts/main.js
> +        this.particles = "0";
Defined as a string here, but only updated with integers later

2020-10-13 20:25 UTC, kolayne commented on scripts/main.js
> +            while (scene.children.length > 5) {
Will you have to update this number each time you add some new objects (like cameras, lights, etc) to the simulation? Is there a way to check the condition you actually want to check (`are there any objects with the name "point"`, as far as I'm concerned)?

2020-10-13 20:25 UTC, kolayne commented on scripts/main.js
> +    var cl = gui.addColor(fizzyText, "color").name("Color");
`cl` doesn't seem a good name for the variable to me

2020-10-13 20:25 UTC, kolayne commented on scripts/main.js
> +        while (scene.children.length > 5) {
Same as one of the above

2020-10-13 20:25 UTC, kolayne commented on scripts/main.js
> +        while (scene.children.length > 5) {
Same as one of the above

2020-10-13 20:25 UTC, kolayne commented on scripts/main.js
> +            while (scene.children.length > 5) {
Same as one of the above

2020-10-13 20:25 UTC, kolayne commented on scripts/main.js
> +                fizzyText.particles = data[FrameId]["x"].length;
Something is wrong with either logic or variables naming: `particles` should be an array or something alike, but is assigned to an integer

2020-10-13 20:25 UTC, kolayne commented on scripts/main.js
> +                fizzyText.particles = data["x"].length;
Same as above

2020-10-13 20:25 UTC, kolayne commented on scripts/main.js
> +};
No newline at the end of file

2020-10-14 06:46 UTC, pavtiger commented on scripts/main.js
> +    camera.rotation.y = 3.14;
It is a bit magic, on line 1 I change y position of the camera, however on line 2 - rotation of the camera.

2020-10-14 07:26 UTC, kolayne commented on scripts/main.js
> +    camera.rotation.y = 3.14;
Oops, sorry, I didn't notice the difference between the lines

2020-10-16 08:57 UTC, merged